/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import customer.customerviwe;
import javax.swing.JButton;

/**
 *
 * @author ASUS
 */
public class front extends javax.swing.JFrame {

    /**
     * Creates new form front
     */
    public front() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btncus = new javax.swing.JButton();
        btnstore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btncart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btneco = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnexpen = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));
        setLocation(new java.awt.Point(335, 110));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("Customer");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 100, 26);

        btncus.setBackground(new java.awt.Color(204, 204, 255));
        btncus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-circled-user-male-skin-type-7-96.png"))); // NOI18N
        btncus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncusActionPerformed(evt);
            }
        });
        jPanel1.add(btncus);
        btncus.setBounds(30, 20, 80, 70);

        btnstore.setBackground(new java.awt.Color(204, 204, 255));
        btnstore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-store-96.png"))); // NOI18N
        jPanel1.add(btnstore);
        btnstore.setBounds(160, 20, 82, 71);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Store");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 100, 80, 30);

        btncart.setBackground(new java.awt.Color(204, 204, 255));
        btncart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cart-96.png"))); // NOI18N
        jPanel1.add(btncart);
        btncart.setBounds(300, 20, 80, 71);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setText("Cart");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 100, 80, 26);

        btneco.setBackground(new java.awt.Color(204, 204, 255));
        btneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-economy-96.png"))); // NOI18N
        jPanel1.add(btneco);
        btneco.setBounds(450, 20, 90, 70);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setText("Economy");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(440, 100, 101, 30);

        btnexpen.setBackground(new java.awt.Color(204, 204, 255));
        btnexpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cost-64.png"))); // NOI18N
        jPanel1.add(btnexpen);
        btnexpen.setBounds(610, 20, 90, 70);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setText("Expenditures");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(590, 100, 140, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-290, -40, 1824, 1216);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncusActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btncusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncart;
    private javax.swing.JButton btncus;
    private javax.swing.JButton btneco;
    private javax.swing.JButton btnexpen;
    private javax.swing.JButton btnstore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
public JButton getBtncus() {
        return btncus;
    }
public JButton getbtnstore() {
        return btnstore;
    }
    public JButton btnbill() {
        return btncart;
    }
    public JButton btneco() {
        return btneco;
    }
     public JButton btnexpen() {
        return btnexpen;
    }
    
    
}


