/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package store;

import customer.*;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.DefaultListModel;

import javax.swing.JList;
import javax.swing.JTable;

import javax.swing.JTextField;


/**
 *
 * @author ASUS
 */
public class itemupdate extends javax.swing.JFrame {

    /**
     * Creates new form custupdate
     */
      private DefaultListModel<String> listModel;

    public itemupdate() {
        initComponents();
        listModel = new DefaultListModel<>();
        jList1.setModel(listModel);
        // Add ListSelectionListener to jList1
        jList1.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                String selectedValue = jList1.getSelectedValue();
                if (selectedValue != null) {
                    txtsrchitem.setText(selectedValue);
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnupdate = new javax.swing.JButton();
        txtupname = new javax.swing.JTextField();
        lblcusname = new javax.swing.JLabel();
        txtupqty = new javax.swing.JTextField();
        lblcustp = new javax.swing.JLabel();
        txtupprice = new javax.swing.JTextField();
        btnclose = new javax.swing.JButton();
        lblcusemail = new javax.swing.JLabel();
        txtsrchitem = new javax.swing.JTextField();
        lblcusname1 = new javax.swing.JLabel();
        btnsrch = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        txtcost = new javax.swing.JTextField();
        lblcusemail1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 250));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnupdate.setBackground(new java.awt.Color(102, 255, 255));
        btnupdate.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnupdate.setText("Update ");
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 372, 91, 36));
        getContentPane().add(txtupname, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 174, 285, 31));

        lblcusname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcusname.setText("Item Name:");
        getContentPane().add(lblcusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 174, 139, 31));
        getContentPane().add(txtupqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 218, 285, 31));

        lblcustp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcustp.setText(" Item Quantity:");
        getContentPane().add(lblcustp, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 222, 139, -1));
        getContentPane().add(txtupprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 320, 285, 34));

        btnclose.setBackground(java.awt.Color.red);
        btnclose.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setText("X");
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 0, -1, -1));

        lblcusemail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcusemail.setText("Price");
        getContentPane().add(lblcusemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 318, 139, 36));
        getContentPane().add(txtsrchitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 201, 31));

        lblcusname1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcusname1.setText(" Item Name:");
        getContentPane().add(lblcusname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 102, 39));

        btnsrch.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnsrch.setText("Search");
        btnsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, 36));

        btndelete.setBackground(new java.awt.Color(102, 255, 255));
        btndelete.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 372, 82, 36));
        getContentPane().add(txtcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 267, 285, 34));

        lblcusemail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcusemail1.setText("Cost");
        getContentPane().add(lblcusemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 267, 139, 36));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 290, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsrchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itemupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itemupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itemupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itemupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new itemupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsrch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblcusemail;
    private javax.swing.JLabel lblcusemail1;
    private javax.swing.JLabel lblcusname;
    private javax.swing.JLabel lblcusname1;
    private javax.swing.JLabel lblcustp;
    private javax.swing.JTextField txtcost;
    private javax.swing.JTextField txtsrchitem;
    private javax.swing.JTextField txtupname;
    private javax.swing.JTextField txtupprice;
    private javax.swing.JTextField txtupqty;
    // End of variables declaration//GEN-END:variables

        public JTextField getcode() {
        return txtsrchitem;
    }
         public JList<String> getJList() {
        return jList1;
    }
          public DefaultListModel<String> getListModel() {
        return listModel;
    }

    
    public JButton getBtncus() {
        return btnupdate;
    }
    public JButton getBtnclose() {
        return btnclose;
    }
    public JButton getserch() {
        return btnsrch;
    }
    
    public JTextField getsrchnme() {
        return txtsrchitem;
    }

    public JTextField getupname() {
        return txtupname;
    }
    public JTextField getuptp() {
        return txtupqty;
    }
    public JTextField getupemail() {
        return txtupprice;
    }
    
    public JButton getdelete() {
        return btndelete;
    }
    public JTextField getcost() {
        return txtcost;
    }


}
